# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20180130_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Şehir', 'verbose_name_plural': 'Şehirler'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'İlçe', 'verbose_name_plural': 'İlçeler'},
        ),
    ]
